import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import NavBar from './navbar';
import { getServerSession } from 'next-auth';
import { authOptions } from "@/pages/api/auth/[...nextauth]"



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  
//1. 서버컴포넌트일때 유저의 정보 가져오기
  let session = await getServerSession(authOptions)//현재 로그인된 유저이름, 이메일 등이 남음
  //유저의 이름이나 이메일 등을 가져다 쓸 수 있음

//2. 클라이언트컴포넌트일때는 <SessionProvider> 로 하위 컴포넌트를 감싸면 하위컴포넌트중 클라이언트컴포넌트에서 useSession()이사용가능

  return (
    <html lang="en"> 
      <body className={inter.className}>
        <NavBar session={session}/>

        
        {children}
        </body>
    </html>
  )
}
