'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import { useRouter } from "next/navigation"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  let router = useRouter()


  return (
    <html lang="en"> 
      <body className={inter.className}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link>
          <Link href="#" onClick={()=>{
            router.back()
          }}> ← </Link>  
        </div>
        {children}
        </body>
    </html>
  )
}
